# <u> Use only those concepts which have been taught till now </u>

In [ ]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [ ]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
# Your code here
np.average(random_integers[:5,2:4])

286058.5

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points
arr2d=np.array(np.random.randint(5,20,(10,10)))
print(arr2d)

[[19 12 10 16  7 12 10 19  5  9]
 [ 7  7  5 14 16  6  5  8  6  8]
 [ 6 16  6 11  5  7 11 15 18 14]
 [ 6 19  8  6  6  6  6  6 16 16]
 [18 11 10 12 10  9 11 18  6 14]
 [18 16  6 17  8 19 11 19 17 13]
 [ 6 14  6 17  5 16 18 18 14 13]
 [ 8 15 14  9 17  5  7 14  5 13]
 [19 19  6 19  6  9 11 15 13 18]
 [10  5  8 10 12  5 13 10  8 19]]


In [ ]:
from numpy.lib import math
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
list=[]
for i in range(10):
  for j in range(10):
    if(j==9 and i!=9):
      a=math.sqrt(((arr2d[i][j]-0)**2)+((arr2d[i][j]-arr2d[i+1][j])**2))
    elif(i==9 and j!=9):
      a=math.sqrt(((arr2d[i][j]-arr2d[i][j+1])**2)+((arr2d[i][j]-0)**2))
    elif(i==9 and j==9):
       a=arr2d[i][j]
    else:
      a=(math.sqrt(((arr2d[i][j]-arr2d[i][j+1])**2)+((arr2d[i][j]-arr2d[i+1][j])**2)))
    list.append(a)
euclidian=np.array(list)
np.reshape(euclidian,(10,10))

array([[13.89244399,  5.38516481,  7.81024968,  9.21954446, 10.29563014,
         6.32455532, 10.29563014, 17.80449381,  4.12310563,  9.05538514],
       [ 1.        ,  9.21954446,  9.05538514,  3.60555128, 14.86606875,
         1.41421356,  6.70820393,  7.28010989, 12.16552506, 10.        ],
       [10.        , 10.44030651,  5.38516481,  7.81024968,  2.23606798,
         4.12310563,  6.40312424,  9.48683298,  4.47213595, 14.14213562],
       [17.69180601, 13.60147051,  2.82842712,  6.        ,  4.        ,
         3.        ,  5.        , 15.62049935, 10.        , 16.1245155 ],
       [ 7.        ,  5.09901951,  4.47213595,  5.38516481,  2.23606798,
        10.19803903,  7.        , 12.04159458, 13.60147051, 14.03566885],
       [12.16552506, 10.19803903, 11.        ,  9.        , 11.40175425,
         8.54400375, 10.63014581,  2.23606798,  5.        , 13.        ],
       [ 8.24621125,  8.06225775, 13.60147051, 14.4222051 , 16.2788206 ,
        11.18033989, 11.        ,  5.65685425

In [ ]:
print(arr2d)

[[19 12 10 16  7 12 10 19  5  9]
 [ 7  7  5 14 16  6  5  8  6  8]
 [ 6 16  6 11  5  7 11 15 18 14]
 [ 6 19  8  6  6  6  6  6 16 16]
 [18 11 10 12 10  9 11 18  6 14]
 [18 16  6 17  8 19 11 19 17 13]
 [ 6 14  6 17  5 16 18 18 14 13]
 [ 8 15 14  9 17  5  7 14  5 13]
 [19 19  6 19  6  9 11 15 13 18]
 [10  5  8 10 12  5 13 10  8 19]]


In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.
list1=[]
for i in range(10):
  for j in range(10):
    if(j==9 and i!=9):
      a=(abs(arr2d[i][j]-0))+(abs(arr2d[i][j]-arr2d[i+1][j]))
    elif(i==9 and j!=9):
      a=(abs(arr2d[i][j]-arr2d[i][j+1]))+(abs(arr2d[i][j]-0))
    elif(i==9 and j==9):
       a=arr2d[i][j]
    else:
      a=(abs(arr2d[i][j]-arr2d[i][j+1]))+(abs(arr2d[i][j]-arr2d[i+1][j]))
    list1.append(a)
print(list)
manhattan=np.array(list1)
np.reshape(manhattan,(10,10))

[13.892443989449804, 5.385164807134504, 7.810249675906654, 9.219544457292887, 10.295630140987, 6.324555320336759, 10.295630140987, 17.804493814764857, 4.123105625617661, 9.055385138137417, 1.0, 9.219544457292887, 9.055385138137417, 3.605551275463989, 14.866068747318506, 1.4142135623730951, 6.708203932499369, 7.280109889280518, 12.165525060596439, 10.0, 10.0, 10.44030650891055, 5.385164807134504, 7.810249675906654, 2.23606797749979, 4.123105625617661, 6.4031242374328485, 9.486832980505138, 4.47213595499958, 14.142135623730951, 17.69180601295413, 13.601470508735444, 2.8284271247461903, 6.0, 4.0, 3.0, 5.0, 15.620499351813308, 10.0, 16.1245154965971, 7.0, 5.0990195135927845, 4.47213595499958, 5.385164807134504, 2.23606797749979, 10.198039027185569, 7.0, 12.041594578792296, 13.601470508735444, 14.035668847618199, 12.165525060596439, 10.198039027185569, 11.0, 9.0, 11.40175425099138, 8.54400374531753, 10.63014581273465, 2.23606797749979, 5.0, 13.0, 8.246211251235321, 8.06225774829855, 13.6014

array([[19,  7, 11, 11, 14,  8, 14, 25,  5, 10],
       [ 1, 11, 10,  5, 21,  2,  9,  9, 14, 14],
       [10, 13,  7, 11,  3,  5,  9, 12,  6, 16],
       [25, 19,  4,  6,  4,  3,  5, 22, 10, 18],
       [ 7,  6,  6,  7,  3, 12,  7, 13, 19, 15],
       [14, 12, 11,  9, 14, 11, 15,  3,  7, 13],
       [10,  9, 19, 20, 23, 13, 11,  8, 10, 13],
       [18,  5, 13, 18, 23,  6, 11, 10, 16, 18],
       [ 9, 27, 15, 22,  9,  6,  6,  7, 10, 19],
       [15,  8, 10, 12, 19, 13, 16, 12, 19, 19]])

## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here


# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..
array_10=np.random.randint(1,high=5000, size=(10, 10))
print(array_10)
print("\n")
k=3
f=3
for i in range(8):
  for j in range(8):
    print(array_10[i:i+3,j:j+3])
    print("\n")



[[2662 1337 4955 1096 4473 4002 1264 2255 3595  832]
 [3439 4190 2197 1876 2503 4938 2097 3751 1531  927]
 [4519 2190 2885 1130 1320 3278  410 1151 1749   97]
 [4128 2704  703 4582 4575 1369 4304  919 3007 3113]
 [2441   99 3560 3894 4617 2219 2643 4338  386 4819]
 [3643 3528 1705 2548 2386 3918  241 3177 3880 3838]
 [1914  328  893  772 1033 1991 3165 4836  401 2366]
 [1103 3120 2474 1253  319 3861 2232 3889 4320 3306]
 [ 954 1750 1106 4088 3422 4918 4545 2738 2341 4977]
 [ 391  168  531 3551 3544 4680 2570 4613 2543 2120]]


[[2662 1337 4955]
 [3439 4190 2197]
 [4519 2190 2885]]


[[1337 4955 1096]
 [4190 2197 1876]
 [2190 2885 1130]]


[[4955 1096 4473]
 [2197 1876 2503]
 [2885 1130 1320]]


[[1096 4473 4002]
 [1876 2503 4938]
 [1130 1320 3278]]


[[4473 4002 1264]
 [2503 4938 2097]
 [1320 3278  410]]


[[4002 1264 2255]
 [4938 2097 3751]
 [3278  410 1151]]


[[1264 2255 3595]
 [2097 3751 1531]
 [ 410 1151 1749]]


[[2255 3595  832]
 [3751 1531  927]
 [1151 1749   97]]


[[3439 4190

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
# Your function below
nearest=501
row=int(input("Enter row size:"))
column=int(input("Enter column size:"))
array=np.random.randint(10,500, size=(row,column))
print(array)
for i in range(row):
  for j in range(column):
    compare=array[i][j]
    for i in range(row):
      for j in range(column):
        if(compare-array[i][j]!=0 and compare-array[i][j]<nearest):
          nearest=compare-array[i][j]
print(nearest+501)



Enter row size:1
Enter column size:15
[[ 59 424 284  25 124 302  27 351 459 326 290 274  41  14 413]]
56
